### ISSUE TITLE
Large repos cause app to crash?

### ISSUE THREAD

**Issue by KTachibanaM** [cloud-emoticon/cloudemoticon-android#68]

**Comment by xymopen** [comment]
Is this cause by this bug?

```
01-17 22:43:04.900 25323 25323 E AndroidRuntime: FATAL EXCEPTION: main
01-17 22:43:04.900 25323 25323 E AndroidRuntime: Process: org.ktachibana.cloudemoji, PID: 25323
01-17 22:43:04.900 25323 25323 E AndroidRuntime: java.lang.RuntimeException: android.os.TransactionTooLargeException: data parcel size 719368 bytes
01-17 22:43:04.900 25323 25323 E AndroidRuntime: 	at android.app.ActivityClient.activityStopped(ActivityClient.java:86)
01-17 22:43:04.900 25323 25323 E AndroidRuntime: 	at android.app.servertransaction.PendingTransactionActions$StopInfo.run(PendingTransactionActions.java:143)
01-17 22:43:04.900 25323 25323 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:938)
01-17 22:43:04.900 25323 25323 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:99)
01-17 22:43:04.900 25323 25323 E AndroidRuntime: 	at android.os.Looper.loopOnce(Looper.java:201)
01-17 22:43:04.900 25323 25323 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:288)
01-17 22:43:04.900 25323 25323 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:8005)
01-17 22:43:04.900 25323 25323 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
01-17 22:43:04.900 25323 25323 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
01-17 22:43:04.900 25323 25323 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1039)
01-17 22:43:04.900 25323 25323 E AndroidRuntime: Caused by: android.os.TransactionTooLargeException: data parcel size 719368 bytes
01-17 22:43:04.900 25323 25323 E AndroidRuntime: 	at android.os.BinderProxy.transactNative(Native Method)
01-17 22:43:04.900 25323 25323 E AndroidRuntime: 	at android.os.BinderProxy.transact(BinderProxy.java:571)
01-17 22:43:04.900 25323 25323 E AndroidRuntime: 	at android.app.IActivityClientController$Stub$Proxy.activityStopped(IActivityClientController.java:1297)
01-17 22:43:04.900 25323 25323 E AndroidRuntime: 	at android.app.ActivityClient.activityStopped(ActivityClient.java:83)
01-17 22:43:04.900 25323 25323 E AndroidRuntime: 	... 9 more
```
